services:
    desafio_b2bit_db:
        image: mysql:9.6.0
        container_name: desafio_b2bit_db
        ports:
            - "3306:3306"
        environment: 
            - MYSQL_DATABASE=b2bit_db
            - MYSQL_USER=b2bit_db_user
            - MYSQL_PASSWORD=6y6RnXmYZ49
            - MYSQL_ROOT_PASSWORD=0G2B3hK7cFud
        volumes:
            - ./volumes/db:/var/lib/mysql
        networks: 
            - desafio_b2bit_network
    
    desafio_b2bit_api:
        build: "."
        depends_on: 
            - desafio_b2bit_db
        container_name: desafio_b2bit_api
        ports:
            - "80:80"
        networks: 
            - desafio_b2bit_network
    
    desafio_b2bit_cache:
        image: redis:8.6
        ports:
            - "6379:6379"
        networks:
            - desafio_b2bit_network

networks: 
    desafio_b2bit_network:
        driver: bridge