name: Pylint

on: [push]

jobs:
  pylint:
    if: false
    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Configurando o Python 3
      uses: actions/setup-python@v6
      with:
        python-version: "3.14"
    - name: Instalando dependencias
      run: |
        cd app
        python -m pip install --upgrade pip
        pip install poetry
        poetry install --with dev
    - name: Analisar o código com pylint
      run: |
        cd app
        poetry run pylint $(git ls-files '*.py')