name: Testar

on: [push]

jobs:
  testando:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Configurando o Python 3
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Instalando dependencias
      run: |
        cd app
        python -m pip install --upgrade pip
        pip install poetry
        poetry install --with dev
    - name: Executando testes
      run: |
        poetry run pytest